---
author: "Florian Fox"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
pdf_document: default
title: 'Master Thesis: A Causal Test of the Law of 1/n and its Mechanisms'
toc: yes
toc_float: yes
---

# Load data and packages

```{r Packages}
library(tidyverse)
library(haven)
library(ggcorrplot)
library(reshape2)
```

```{r Data}
data <-
  haven::read_stata("data/gemeinderatswahlen_alldata.dta") %>%
  select(-starts_with("pct_votes"), -starts_with("seats_"),
         -state_election, -voters_state, -valid_votes_state, -turnout_state, -ends_with("_state_sh"),
         -pattern, -ln_inh_tot, -Elec_data_no_elec_iteration, -class, -ags_length)
```

```{r Options}
options(scipen = 20)
```



# First look at the data

```{r First look}
glimpse(data)
```

## Univaraite statistics

## NAs

```{r}
data %>%
  summarize(across(.cols = everything(),
                   .fns = ~sum(is.na(.))/n()
                   ))
data %>%
  group_by(state) %>%
  summarize(across(.cols = everything(),
                   .fns = ~sum(is.na(.))/n()
                   ))
data %>%
  group_by(year) %>%
  summarize(across(.cols = everything(),
                   .fns = ~sum(is.na(.))/n()
                   ))
data %>%
  group_by(state, year) %>%
  summarize(across(.cols = everything(),
                   .fns = ~sum(is.na(.))/n()
                   ))
```


## Numeric variables

```{r}
summarize2 <- function(x, na.rm = TRUE) {
  result <- c(
    Min = min(x, na.rm = na.rm),
    Q25 = quantile(x, probs = 0.25, na.rm = na.rm),
    Median = median(x, na.rm = na.rm),
    Q75 = quantile(x, probs = 0.75, na.rm = na.rm),
    Max = max(x, na.rm = na.rm),
    Mean = mean(x, na.rm = na.rm),
    SD = sd(x, na.rm = na.rm),
    N = length(x) - sum(is.na(x)),
    No_NA = sum(is.na(x))
  )
}
```
```{r Univariate stats}
dim(data)
data %>%
  summarize(
    across(
      where(is.numeric),
      summarize2
    )
  ) %>%
  mutate(Stat = c("Min", "1st Quar", "Median", "3rd Quar", "Max", "Mean", "SD", "n", "No_NA"),
         .before = No)
```

```{r Histogram}
data  %>%
  select(where(is.numeric)) %>%
  reshape2::melt(.) %>%
  ggplot(., aes(x = value)) + 
    facet_wrap(~variable, scales = "free") + 
    geom_histogram()
```



## Factors


```{r}
data %>%
  select(-where(is.numeric), -starts_with("ags"), -town) %>%
  sapply(., function(x) table(x, useNA = "always"))
```

# Bivariate descriptive statistics

## Correlations

```{r}
data %>%
  select(where(is.numeric)) %>%
  cor(., use = "pairwise.complete.obs") %>%
  ggcorrplot::ggcorrplot(
    .,
    colors = c("red", "white", "blue"),
    lab = TRUE,
    digits = 1
    )
```


```{r}

```
